"""Data models for Jev AI email flow automation and Corporate Actions workflow."""

from __future__ import annotations
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class EmailAttachment(BaseModel):
    """Metadata and content for email attachments."""

    filename: str
    content_type: str = "application/pdf"
    size_bytes: int = 0
    extracted_text: Optional[str] = None
    is_mock: bool = False


class EmailMessage(BaseModel):
    """Normalized email message structure."""

    id: str
    subject: str = ""
    sender: str = ""
    recipient: str = ""
    date: Optional[str] = None
    body: str = ""
    raw_headers: Dict[str, str] = Field(default_factory=dict)
    source_file: Optional[str] = None
    attachments: List[EmailAttachment] = Field(default_factory=list)
    normalized_text: str = ""
    ocr_applied: bool = False
    ocr_extracted_text: str = ""

    @property
    def preview(self) -> str:
        """Short preview snippet of email body."""
        clean = " ".join(self.body.split())
        return clean[:140] + ("..." if len(clean) > 140 else "")

    @property
    def raw_text_envelope(self) -> str:
        """Raw envelope combining sender, subject, and body text."""
        envelope = f"From: {self.sender}\nSubject: {self.subject}\nBody: {self.body}"
        if self.attachments:
            att_names = ", ".join(a.filename for a in self.attachments)
            envelope += f"\nAttachments: {att_names}"
        return envelope

    @property
    def has_attachments(self) -> bool:
        """Check if message contains attachments."""
        return len(self.attachments) > 0


class IngestionGateResult(BaseModel):
    """Jev AI Ingestion Gate decision (Stage 1)."""

    requires_heavy_ocr: bool
    ocr_probability: float  # Noul: 0.0 to 1.0 calibrated
    reasoning: str = ""
    latency_ms: float = 0.0
    mode: str = "simulator"
    raw_answer: Dict[str, Any] = Field(default_factory=dict)


class CoreDecisionResult(BaseModel):
    """Jev AI Core Decision output matrix (Stage 3)."""

    event_type: str  # Choice: Cash_Dividend, Stock_Dividend, Merger_Acquisition, Ticker_Change, Spam_Or_Irrelevant
    event_type_confidence: float = 0.0
    event_type_probabilities: Dict[str, float] = Field(default_factory=dict)

    is_actionable: bool  # Noul: True (Needs reply/election) or False (Informational only)
    is_actionable_probability: float = 0.0

    urgency_score: int = 1  # Score: Scale 1-10 of how critical timeline is (10 = within 48h)
    urgency_confidence: float = 0.0
    urgency_probabilities: Dict[int, float] = Field(default_factory=dict)

    latency_ms: float = 0.0
    mode: str = "simulator"
    raw_answers: Dict[str, Any] = Field(default_factory=dict)


class ClientNoticeDraft(BaseModel):
    """Structured client election email draft generated by Gemini (Stage 4 - Actionable)."""

    subject: str
    recipient_role: str = "Valued Clients / Beneficial Owners"
    event_summary: str
    election_options: List[str] = Field(default_factory=list)
    deadline: str
    instructions: str
    full_email_body: str
    generated_by: str = "Gemini LLM"
    generated_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class HumanInTheLoopItem(BaseModel):
    """Manual exception handling / audit queue item (Stage 4 - HITL)."""

    queue_id: str
    reason: str  # "Informational Notice", "Low Confidence Classification", "High Financial Risk/Exception"
    risk_level: str = "MEDIUM"  # "LOW", "MEDIUM", "HIGH", "CRITICAL"
    clarification_needed: str
    suggested_action: str
    status: str = "PENDING_REVIEW"
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class AuditTrailStep(BaseModel):
    """Structured audit trail step recording decision, options, and actions."""

    step: int
    stage: str
    name: str
    primitive: str = ""
    question: str = ""
    options: List[Dict[str, Any]] = Field(default_factory=list)
    selected_option: str = ""
    selected_score: str = ""
    scores: Dict[str, Any] = Field(default_factory=dict)
    decision: str = ""
    action_taken: str = ""
    latency_ms: float = 0.0
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class CorporateActionFlowResult(BaseModel):
    """End-to-end execution record for the Corporate Action Email Flow."""

    email_id: str
    subject: str
    sender: str
    ingestion_gate: IngestionGateResult
    ocr_applied: bool
    normalized_text_preview: str
    core_decision: CoreDecisionResult
    route: str  # "GEMINI_CLIENT_NOTICE" | "HUMAN_IN_THE_LOOP"
    client_notice: Optional[ClientNoticeDraft] = None
    hitl_item: Optional[HumanInTheLoopItem] = None
    total_latency_ms: float = 0.0
    processed_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    audit_trail: List[AuditTrailStep] = Field(default_factory=list)


class JevDecisionDetails(BaseModel):
    """Structured decision outputs returned by legacy Jev AI System One classifier."""

    category: str
    category_confidence: float = 0.0
    category_probabilities: Dict[str, float] = Field(default_factory=dict)

    urgency_probability: float = 0.0  # Noul: 0.0 to 1.0 calibrated
    severity_score: int = 1  # Score: 1 to 5
    severity_confidence: float = 0.0
    severity_probabilities: Dict[int, float] = Field(default_factory=dict)

    escalation_probability: float = 0.0  # Noul: 0.0 to 1.0 calibrated

    suggested_action: str
    suggested_action_confidence: float = 0.0
    suggested_action_probabilities: Dict[str, float] = Field(default_factory=dict)

    latency_ms: float = 0.0
    model: str = "jev-system-one"
    mode: str = "simulator"  # "live" | "simulator"
    raw_answers: Dict[str, Any] = Field(default_factory=dict)


class WorkflowAction(BaseModel):
    """Post-classification workflow decisions, routing, and alert actions."""

    target_queue: str
    tags: List[str] = Field(default_factory=list)
    escalate_to_human: bool = False
    alert_level: str = "INFO"  # "INFO", "WARNING", "CRITICAL"
    reasoning: List[str] = Field(default_factory=list)
    suggested_action: str = ""
    status: str = "PROCESSED"
    executed_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class ProcessedEmailRecord(BaseModel):
    """Aggregate record combining parsed email, Jev classification, and workflow execution."""

    email: EmailMessage
    classification: JevDecisionDetails
    workflow: WorkflowAction
